// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/base/Avatar.vue')['default']
    AvatarUpload: typeof import('./src/components/business/AvatarUpload.vue')['default']
    BaseBack: typeof import('./src/components/base/BaseBack.vue')['default']
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseConfirm: typeof import('./src/components/base/BaseConfirm.vue')['default']
    BaseDialog: typeof import('./src/components/base/BaseDialog.vue')['default']
    BaseDot: typeof import('./src/components/base/BaseDot.vue')['default']
    BaseDrawer: typeof import('./src/components/base/BaseDrawer.vue')['default']
    BaseEmpty: typeof import('./src/components/base/BaseEmpty.vue')['default']
    BaseIcon: typeof import('./src/components/base/BaseIcon.vue')['default']
    BaseTag: typeof import('./src/components/base/BaseTag.vue')['default']
    BaseTitle: typeof import('./src/components/base/BaseTitle.vue')['default']
    CountTo: typeof import('./src/components/base/CountTo.vue')['default']
    IconCustomDownload: typeof import('~icons/custom/download')['default']
    IconCustomExit: typeof import('~icons/custom/exit')['default']
    IconCustomLogo: typeof import('~icons/custom/logo')['default']
    IconCustomMenuFold: typeof import('~icons/custom/menu-fold')['default']
    IconCustomMenuUnfold: typeof import('~icons/custom/menu-unfold')['default']
    IconCustomPlus: typeof import('~icons/custom/plus')['default']
    IconCustomRefresh: typeof import('~icons/custom/refresh')['default']
    IconCustomSearch: typeof import('~icons/custom/search')['default']
    IconCustomSetting: typeof import('~icons/custom/setting')['default']
    IconCustomUser: typeof import('~icons/custom/user')['default']
    ImageCaptcha: typeof import('./src/components/business/ImageCaptcha.vue')['default']
    Overflow: typeof import('./src/components/base/Overflow.vue')['default']
    Pagination: typeof import('./src/components/base/Pagination.vue')['default']
  }
}

export { }
